import { Rubik } from 'next/font/google'

const rubik = Rubik({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: 'Create Gsap Animation',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  )
}
